config/routes.rb
Todo::Application.routes.draw do

resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name, :description
  validates_presence_of :name 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end
  def show
    @item = Item.find(params[:id])
  end
  def new
    @item = Item.new()
  end
  def create
    @item = Item.new(params[:item])
    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])

  end

  def update
    @item = Item.find(params[:id])
    if@item.update_attributes(params[:item])
      redirect_to items_path
    else 
      render :edit 
    end
  end

  def destroy
    @item = Item.find(params[:id])
    if @item.destroy
      redirect_to items_path
    else 
      raise "Could not delete #{item.name}"
    end
  end
end

  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%=form_for @item do |f| %>
  <%=f.label :name %>
  <%=f.text_field  :name %><br/>
   <%=f.label :description %>
  <%=f.text_field  :description %>
  <%=f.submit%>
<%end%>

app/views/items/edit.html.erb
<h1>Edit it here</h1>
<%= render "form" %>

app/views/items/index.html.erb
<h1>All my Items</h1>
<%=link_to "New", new_item_path %>
<ul>
  <% @items.each do |item| %>
    <li><%=link_to item.name, item_path(item) %> (<%=item.description%>) <%=link_to "Edit", edit_item_path(item)%> <%= link_to "Destroy", item_path(item), :method => 'delete'%></li>
  <%end%>
</ul>

app/views/items/new.html.erb
<h1>New Item</h1>
<%= render "form" %>

app/views/items/show.html.erb
<h1><%=@item.name%></h1>
<p><%=@item.description%></p>
<%=link_to "Back", items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>